import { KeyboardShortcut } from '../types';

export const DEFAULT_SHORTCUTS: KeyboardShortcut[] = [
  {
    id: 'new_activity',
    key: 'n',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'new_activity',
    description: 'Criar nova atividade / Limpar campos',
    defaultCombo: 'Alt + N',
  },
  {
    id: 'adapt_activity',
    key: 'a',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'adapt_activity',
    description: 'Executar adaptação pedagógica imediata',
    defaultCombo: 'Alt + A',
  },
  {
    id: 'simple_reading',
    key: 'l',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'simple_reading',
    description: 'Abrir / Fechar Modo Leitura Simplificado',
    defaultCombo: 'Alt + L',
  },
  {
    id: 'text_to_speech',
    key: 'v',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'text_to_speech',
    description: 'Ouvir texto em voz alta (Leitor de Tela)',
    defaultCombo: 'Alt + V',
  },
  {
    id: 'save_db',
    key: 's',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'save_db',
    description: 'Salvar no Banco de Dados Local',
    defaultCombo: 'Alt + S',
  },
  {
    id: 'open_db',
    key: 'b',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'open_db',
    description: 'Ver Banco de Dados Local (Atividades Salvas)',
    defaultCombo: 'Alt + B',
  },
  {
    id: 'print_material',
    key: 'p',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'print_material',
    description: 'Imprimir atividade adaptada para sala de aula',
    defaultCombo: 'Alt + P',
  },
  {
    id: 'sensory_break',
    key: 'r',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'sensory_break',
    description: 'Abrir Pausa Sensorial / Respiração Calma',
    defaultCombo: 'Alt + R',
  },
  {
    id: 'shortcuts_help',
    key: 'k',
    altKey: true,
    ctrlKey: false,
    shiftKey: false,
    action: 'shortcuts_help',
    description: 'Abrir Guia e Gerenciador de Atalhos',
    defaultCombo: 'Alt + K',
  },
];
